check-guile.in: exit 2 on errors and direct output to stderr
Return 2 rather than 1 for errors so that 1 will be available for any
future boolean tests (as with say grep).

Direct error message to stderr rather than stdout.

* check-guile.in: send error message to stderr and exit 2 (not 1).

diff --git a/check-guile.in b/check-guile.in
--- a/check-guile.in
+++ b/check-guile.in
@@ -30,8 +30,8 @@ if [ -f "$guile" -a -x "$guile" ] ; then
     echo "Testing $guile ..." "$@"
     echo "with GUILE_LOAD_PATH=$GUILE_LOAD_PATH"
 else
-    echo "ERROR: Cannot execute $guile"
-    exit 1
+    echo "ERROR: Cannot execute $guile" 1>&2
+    exit 2
 fi
 
 # documentation searching ignores GUILE_LOAD_PATH.
